PowerBIEmbedding/DailyReporterPro/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using DailyReporterPro.Models;

namespace DailyReporterPro.Controllers {
  public class ReportsController : Controller {

    public async Task<ActionResult> Index(string ReportId, string DatasetId) {
      var viewModel = await PbiEmbeddedManager.GetReports(ReportId, DatasetId);
      return View(viewModel);
    }

  }
}

PowerBIEmbedding/DailyReporterPro/Views/Reports/Index.cshtml
@model DailyReporterPro.Models.ReportsViewModel

<!-- left mav menu -->
<div id="leftNavContainer" class="col-md-2">

  <!-- create reports navigation menu with server-side code in initial request for reports controller -->
  <div class="leftNavSection">
    <div class="leftNavSectionHeader">
      <div class="leftNavIcon fa fa-bar-chart"></div>
      <div class="leftNavPageNavButtons leftNavItem">
        <span id="new-report-button" class="pull-right">
          <!-- <span id="new-report" class="fa fa-plus" >&nbsp;@Html.ActionLink("NEW", "Create", "Reports")</span> -->
          <a id="create-new-report" class="btn btn-sm" href="#">
            <i class="fa fa-plus"></i>New
          </a>
        </span>
      </div>
      <div class="leftNavTitle leftNavItem">Reports</div>
    </div>
    <ul id="reports" class="leftNavMenu leftNavItem">
      @foreach (var report in Model.Reports) {
        var reportClass = Request.QueryString["reportId"] == report.Id ? "activeReport" : "";
      <li class="@reportClass">
        @Html.ActionLink(report.Name, "Index", new { reportId = report.Id })
      </li>
      }
    </ul>
  </div>

  @if (@Model.CurrentReport != null) {
    <div id="loaded-report-panel" hidden="hidden">
      <div class="leftNavSection">
        <div class="leftNavSectionHeader">
          <div class="leftNavIcon fa fa-wrench"></div>
          <div class="leftNavTitle leftNavItem">Configuration</div>
        </div>
        <div class="leftNavMenu leftNavItem ">
          <div>
            <label>
              <input id="setting-shownav" type="checkbox" /> Show Navigation
            </label>
          </div>
          <div>
            <label>
              <input id="setting-showfilterpane" type="checkbox" /> Show Filter Pane
            </label>
          </div>
        </div>
      </div>

      <div class="leftNavSection">
        <div class="leftNavSectionHeader">
          <div class="leftNavIcon fa fa-book"></div>
          <div class="leftNavPageNavButtons leftNavItem">
            <span id="page-navigation-buttons" class="pull-right">
              <span id="goto-prev-page" class="fa fa-arrow-circle-left"></span>
              <span>&nbsp;</span>
              <span id="goto-next-page" class="fa fa-arrow-circle-right"></span>
            </span>
          </div>
          <div class="leftNavTitle leftNavItem">Pages</div>

        </div>
        <div>
          <ul id="page-navigation" class="leftNavMenu leftNavItem">
            <!-- report pages loaded using onReportLoaded event handler -->
          </ul>

        </div>
      </div>
    </div>
  }

  <div id="report-loading-message" hidden="hidden">
    <i class="fa fa-spinner fa-spin"></i>&nbsp;
    <span>Loading report...</span>
  </div>

</div>

<div id="mainView" class="col-md-10">

  <div id="report-toolbar" hidden="hidden">
    @if (@Model.CurrentReport != null) {
    @Model.CurrentReport.Report.Name
    <span id="reportPageTitle"></span>
    }
    @if (@Model.CurrentReport == null) {
    <text>New Report: <span style="font-size: 0.5em;">(Save reporting using <strong>File > Save As</strong> menu command)</span></text>
}
    <div id="toolbar-buttons" class="pull-right">
      @if (@Model.CurrentReport != null) {
      <a id="editMode" class="btn btn-sm" href="#">
        <i class="fa fa-edit"></i>Edit
      </a>
      <a id="viewMode" class="btn btn-sm" href="#" style="display:none;">
        <i class="fa fa-eye"></i>View
      </a>
      <a id="refreshReport" class="btn btn-sm" href="#">
        <i class="fa fa-refresh"></i>Refresh
      </a>
      <a id="printReport" class="btn btn-sm" href="#">
        <i class="fa fa-print"></i>Print
      </a>
      }
      <a id="fullScreen" class="btn btn-sm" href="#">
        <i class="fa fa-expand"></i>Full Screen
      </a>
    </div>
  </div>

  <div id="reportContainer" hidden="hidden"></div>

  @if (Model.ReportMode == DailyReporterPro.Models.ReportMode.ExistingReport) {
  <script>
      var embedReportId = "@Model.CurrentReport.EmbedConfig.Id";
      var embedUrl = "@Html.Raw(Model.CurrentReport.EmbedConfig.EmbedUrl)";
      var accessToken = "@Model.CurrentReport.EmbedConfig.EmbedToken.Token";
      var reportContainer = document.getElementById('reportContainer');
      // call embedReport utility function defined inside App.ts
      PowerBIEmbedManager.embedReport(embedReportId, embedUrl, accessToken, reportContainer);
  </script>
  }
  @if (Model.ReportMode == DailyReporterPro.Models.ReportMode.NewReport) {
  <script>
      var embedDatasetId = "@Model.CurrentDataset.EmbedConfig.DatasetId";
      var embedUrl = "@Html.Raw(Model.CurrentDataset.EmbedConfig.EmbedUrl)";
      var accessToken = "@Model.CurrentDataset.EmbedConfig.EmbedToken.Token";
      var reportContainer = document.getElementById('reportContainer');
      // call embedReport utility function defined inside App.ts
      PowerBIEmbedManager.createReport(embedDatasetId, embedUrl, accessToken, reportContainer);
  </script>
  }


</div>


<div id="modelCreateNewReport" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Select a Dataset for the New Report</h4>
      </div>
      <div class="modal-body">
        <table id="datasets-table">
          @foreach (var dataset in Model.Datasets) {
            <tr>
              <td>
                <i class="fa fa-database"></i>
                <a href="/reports/?datasetId=@dataset.Id">@dataset.Name</a>
              </td>
            </tr>
          }
        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>